### PR TITLE
Align conda-forge.yml with ignition repo

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The `linux_aarch64` emulate build is taking too much, I switched to cross-compile even there.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin please restart ci

**Comment by Tobias-Fischer** [comment]
Probably makes sense to set 
https://github.com/traversaro/gz-math-feedstock/blob/ec605ba6dae0d67ffea45e7e220fefa6d92ff40f/conda-forge.yml#L2

to linux-64 instead.

**Comment by traversaro** [comment]
> Probably makes sense to set https://github.com/traversaro/gz-math-feedstock/blob/ec605ba6dae0d67ffea45e7e220fefa6d92ff40f/conda-forge.yml#L2
> 
> to linux-64 instead.

I can't find the log, but unfortunatly this resul in an error. I wanted to get a first build with aarch64 in so to unblock the sdormat13 build, then we can investigate the issue in a dedicate PR.

**Comment by traversaro** [comment]
> > Probably makes sense to set https://github.com/traversaro/gz-math-feedstock/blob/ec605ba6dae0d67ffea45e7e220fefa6d92ff40f/conda-forge.yml#L2
> > to linux-64 instead.
> 
> I can't find the log, but unfortunatly this result in an error. I wanted to get a first build with aarch64 in so to unblock the sdormat13 build, then we can investigate the issue in a dedicate PR.

See https://github.com/conda-forge/gz-math-feedstock/pull/4 .

**Pull request merged**
