### PR TITLE
Use cross-compilation also on linux-aarch64

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The `linux-aarch64` build is failing with error:
~~~
2022-10-10T11:33:24.3842812Z Setting up cross-python
2022-10-10T11:33:24.5942197Z ERROR: 'HOST_GNU_TYPE'
~~~

**Comment by Tobias-Fischer** [comment]
Seems like something odd is going on with the pypy cross compilation. Any idea what this problem could be @conda-forge/cross-python?

**Comment by isuruf** [comment]
@mattip, looks like the sysconfigdata is missing `HOST_GNU_TYPE` after the last update

**Comment by mattip** [comment]
> looks like the sysconfigdata is missing `HOST_GNU_TYPE`

Correct. Is there an upstream CI for cross compiling where I can try to add PyPy? It is not sustainable to add the tens of various `./configure` macros one at a time.

**Comment by traversaro** [comment]
Now that the fixed pypy packages were uploaded (see https://github.com/conda-forge/pypy3.6-feedstock/pull/91#issuecomment-1286903933), this should work.

**Pull request merged**
